-- CREATE TABLE address (
--                            id int(11) NOT NULL AUTO_INCREMENT,
--                            street varchar(100) NOT NULL,
--                            city varchar(45) NOT NULL,
--                            PRIMARY KEY (id)
-- );
--
-- CREATE TABLE student (
--                            id int(11) NOT NULL AUTO_INCREMENT,
--                            first_name varchar(50) NOT NULL,
--                            last_name varchar(50) DEFAULT NULL,
--                            email varchar(30) DEFAULT NULL,
--                            address_id int(11) DEFAULT NULL,
--                            PRIMARY KEY (id)
-- );
--
-- CREATE TABLE subject (
--                            id int(11) NOT NULL AUTO_INCREMENT,
--                            subject_name varchar(45) DEFAULT NULL,
--                            marks_obtained double DEFAULT NULL,
--                            student_id int(11) DEFAULT NULL,
--                            PRIMARY KEY (id),
--                            KEY student_id (student_id),
--                            CONSTRAINT subject_ibfk_1 FOREIGN KEY (student_id) REFERENCES student (id)
-- );
--
-- INSERT INTO address VALUES (1,Happy Street,Delhi),(2,2nd Street,Mumbai),(3,3rd Street,Delhi),(4,any street,Mumbai);
-- INSERT INTO student VALUES (1,John,Smith,john@gmail.com,1),(2,Virat,Dave,virat@gmail.com,2),(3,Steve,Martin,steve@gmail.com,3),(4,Sachin,Kumar,sachin@gmail.com,4);
-- INSERT INTO subject VALUES (1,80,Java,1),(2,70,MySQL,1),(3,80,Java,2),(4,70,MySQL,2),(5,70,MongoDB,2),(6,70,MySQL,3),(7,70,MongoDB,3),(8,60,Java,4),(9,50,MongoDB,4);